### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by naninyang** [kr-juso/administrationCode#1]
최근에 https://juso.dev/ 를 알게 되어 해당 API를 가지고 서비스 개발하고 있습니다. API를 만들어 주셔서 감사합니다.

다름이 아니라 행정동 업데이트가 안되고 있는 느낌이 있어서 확인해보니 마지막 디플로이가 1년 전이네요.
행정동 업데이트를 진행해 주시면 감사하겠습니다.

**Comment by YeongCheon** [comment]
안녕하세요.

[여기](https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=101232) 기준으로 업데이트 완료됐습니다.

9d41fc0672b2854abfbe678d3ef382d9a8a8835d
